# Generated by Django 5.1.1 on 2024-09-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='affiliated_clinics',
            field=models.ManyToManyField(related_name='doctors', to='clinics.clinic'),
        ),
    ]
