# Generated by Django 5.1.1 on 2024-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_affiliated_clinics'),
        ('patients', '0003_remove_patient_next_appointment_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='affiliated_patients',
            field=models.ManyToManyField(blank=True, related_name='affiliated_doctors', to='patients.patient'),
        ),
    ]
