# Generated by Django 5.1.1 on 2024-09-17 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_affiliated_patients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='affiliated_patients',
        ),
    ]
