# Generated by Django 5.1.1 on 2024-09-17 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_remove_doctor_affiliated_patients'),
        ('patients', '0003_remove_patient_next_appointment_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='offered_patients',
            field=models.ManyToManyField(to='patients.patient'),
        ),
    ]
