# Generated by Django 5.1.1 on 2024-09-17 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0007_doctor_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='affiliated_clinics',
            field=models.ManyToManyField(related_name='doctors_clinic', to='clinics.clinic'),
        ),
    ]
