# Generated by Django 5.1.1 on 2024-09-20 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('doctors', '0008_alter_doctor_affiliated_clinics'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_address', models.CharField(max_length=255)),
                ('working_days', models.CharField(max_length=100)),
                ('working_hours_start', models.TimeField()),
                ('working_hours_end', models.TimeField()),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='clinics.clinic')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='doctors.doctor')),
            ],
        ),
    ]
