# Generated by Django 5.1.1 on 2024-09-16 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('last_visit_date', models.DateField(blank=True, null=True)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('last_visit_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_visit_doctors', to='doctors.doctor')),
                ('last_visit_procedures', models.ManyToManyField(blank=True, related_name='last_visit_procedures', to='doctors.procedure')),
                ('next_appointment_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_appointment_doctors', to='doctors.doctor')),
                ('next_appointment_procedure', models.ManyToManyField(blank=True, related_name='next_appointment_procedures', to='doctors.procedure')),
            ],
        ),
    ]
