# Generated by Django 5.1.1 on 2024-09-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_affiliated_clinics'),
        ('patients', '0002_patient_clinic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='next_appointment_procedure',
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='next_appointment_procedures',
            field=models.ManyToManyField(blank=True, related_name='next_appointment_patients', to='doctors.procedure'),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ssn_last_4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_visits', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_visit_procedures',
            field=models.ManyToManyField(blank=True, related_name='last_visit_patients', to='doctors.procedure'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_appointment_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_appointments', to='doctors.doctor'),
        ),
    ]
