# Generated by Django 5.1.1 on 2024-09-20 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_doctors_clinic_patients'),
        ('patients', '0004_appointment_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='patients_list', to='clinics.clinic'),
            preserve_default=False,
        ),
    ]
