# Generated by Django 5.1.1 on 2024-09-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0002_clinic_doctors_clinic_patients'),
        ('patients', '0005_alter_patient_clinic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='clinic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients_list', to='clinics.clinic'),
        ),
    ]
